#!/usr/bin/env bash
#
# RealtorOS launch wizard — walks a non-technical user through setup and launch.
# Generated by the /wizard skill.
#
# Run from anywhere:
#   bash scripts/launch-wizard.sh
# or, after chmod +x:
#   ./scripts/launch-wizard.sh

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.realtor-preferences.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# shellcheck source=realtor-logo.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/realtor-logo.sh"

banner() {
  _clear
  realtor_show_logo "$BOLD" "$DIM" "$BLUE" "$RESET"
  printf '%s  %s steps — about 5 minutes%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Welcome! This setup will help you chat with AI assistants\n' "$DIM"
  printf '  (like Claude, ChatGPT Codex, or Kimi) right in your web browser.\n\n'
  printf '  Everything stays in your user folder — we do not change system\n'
  printf '  Node or require administrator access (Mac, Linux, WSL).\n\n'
  printf '  We will:\n'
  printf '    • install Node.js in ~/.local (fnm) if needed\n'
  printf '    • make sure your computer is ready\n'
  printf '    • install the browser used for Zillow imports\n'
  printf '    • ask which AI assistants you want to use\n'
  printf '    • check that you are signed in to them\n'
  printf '    • open the chat app for you\n\n'
  printf '  You can stop anytime (Ctrl-C) and come back later — we remember\n'
  printf '  your choices.%s\n' "$RESET"
  note "Full software list & reinstall guide: docs/INSTALL.md"
  pause "Press Enter when you're ready"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Step %s of %s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# Redraw the current step header without advancing the step counter.
stage_refresh() {
  _clear
  printf '\n%s%s▸ Step %s of %s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# Read one key for interactive menus (↑/↓/Space/Enter).
read_key() {
  local k k2
  IFS= read -rsn1 k || return 1
  case "$k" in
    $'\x1b')
      read -rsn1 -t 0.01 k2 || true
      if [[ "$k2" == '[' ]]; then
        read -rsn1 -t 0.01 k2 || true
        case "$k2" in
          A) REPLY=up ;;
          B) REPLY=down ;;
          *) REPLY=other ;;
        esac
      else
        REPLY=other
      fi
      ;;
    ' ') REPLY=space ;;
    ''|$'\n') REPLY=enter ;;
    q|Q) REPLY=quit ;;
    *) REPLY=other ;;
  esac
}

_menu_hide_cursor() {
  [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && tput civis 2>/dev/null || true
}

_menu_show_cursor() {
  [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && tput cnorm 2>/dev/null || true
}

_menu_move_up() {
  local n="$1"
  (( n > 0 )) || return 0
  if command -v tput >/dev/null 2>&1; then
    tput cuu "$n" 2>/dev/null || printf '\033[%dA' "$n"
  else
    printf '\033[%dA' "$n"
  fi
}

# Move cursor up N lines and erase each one (prevents leftover text on redraw).
_menu_clear_lines() {
  local n="$1" i
  (( n > 0 )) || return 0
  _menu_move_up "$n"
  for (( i=0; i<n; i++ )); do
    if command -v tput >/dev/null 2>&1; then
      tput el 2>/dev/null || printf '\033[2K\r'
      if (( i < n - 1 )); then
        tput cud1 2>/dev/null || printf '\033[1B'
      fi
    else
      printf '\033[2K\r'
      if (( i < n - 1 )); then
        printf '\033[1B'
      fi
    fi
  done
}

# Multi-select menu: ↑/↓ move, Space toggle, Enter confirm (at least one required).
# Usage: multiselect PROMPT OUT_VAR_NAME [--default idx ...] -- OPTION ...
# Sets OUT_VAR_NAME to an array of selected option indices.
multiselect() {
  local prompt="$1" out_name="$2"
  shift 2
  local defaults=() options=() parsing_defaults=true

  while (( $# )); do
    if $parsing_defaults && [[ "$1" == "--default" ]]; then
      shift
      while (( $# )) && [[ "$1" != "--" ]]; do
        defaults+=("$1")
        shift
      done
      continue
    fi
    if $parsing_defaults && [[ "$1" == "--" ]]; then
      parsing_defaults=false
      shift
      continue
    fi
    options+=("$1")
    shift
  done

  if [[ ! -t 0 || ! -t 1 || ${#options[@]} -eq 0 ]]; then
    local i choice picked=()
    say "$prompt"
    for i in "${!options[@]}"; do
      note "  $((i + 1)). ${options[$i]}"
    done
    note "  Type numbers separated by spaces, then press Enter."
    printf '  %s> %s' "$BOLD" "$RESET"
    read -r choice || true
    for token in $choice; do
      if [[ "$token" =~ ^[0-9]+$ ]] && (( token >= 1 && token <= ${#options[@]} )); then
        picked+=("$((token - 1))")
      fi
    done
    if (( ${#picked[@]} == 0 )); then
      picked+=(0)
    fi
    eval "$out_name=()"
    for i in "${picked[@]}"; do
      eval "$out_name+=($i)"
    done
    return 0
  fi

  local selected=() cursor=0 i found line_count=0 key
  for i in "${!options[@]}"; do
    selected[i]=0
  done
  for i in "${defaults[@]}"; do
    if [[ "$i" =~ ^[0-9]+$ ]] && (( i >= 0 && i < ${#options[@]} )); then
      selected[i]=1
    fi
  done
  if ! printf '%s' "${selected[@]}" | grep -q '1'; then
    selected[0]=1
  fi

  _menu_hide_cursor
  trap '_menu_show_cursor' RETURN

  while true; do
    if (( line_count > 0 )); then
      _menu_clear_lines "$line_count"
    fi
    line_count=0

    printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
    line_count=$((line_count + 1))
    for i in "${!options[@]}"; do
      local mark=" " prefix="  "
      [[ ${selected[$i]} -eq 1 ]] && mark="x"
      [[ $i -eq $cursor ]] && prefix="${BLUE}> "
      printf '%s[%s] %s\n' "$prefix" "$mark" "${options[$i]}"
      line_count=$((line_count + 1))
    done
    printf '  %sUse ↑/↓ to move, Space to select, Enter to confirm%s\n' "$DIM" "$RESET"
    line_count=$((line_count + 1))

    read_key || continue
    key="$REPLY"
    case "$key" in
      up)    cursor=$(((cursor - 1 + ${#options[@]}) % ${#options[@]})) ;;
      down)  cursor=$(((cursor + 1) % ${#options[@]})) ;;
      space) selected[cursor]=$((1 - selected[cursor])) ;;
      enter)
        found=0
        for i in "${!selected[@]}"; do
          [[ ${selected[$i]} -eq 1 ]] && found=1 && break
        done
        if (( found )); then
          break
        fi
        selected[cursor]=1
        ;;
      quit) break ;;
    esac
  done

  _menu_clear_lines "$line_count"
  eval "$out_name=()"
  for i in "${!selected[@]}"; do
    if [[ ${selected[$i]} -eq 1 ]]; then
      eval "$out_name+=($i)"
    fi
  done
}

# Single-select menu: ↑/↓ move, Enter confirm.
# Usage: select_one PROMPT OUT_VAR_NAME [--default idx] -- OPTION ...
select_one() {
  local prompt="$1" out_name="$2"
  shift 2
  local default_idx=-1 options=() parsing=true

  while (( $# )); do
    if $parsing && [[ "$1" == "--default" ]]; then
      shift
      default_idx="${1:--1}"
      shift
      continue
    fi
    if $parsing && [[ "$1" == "--" ]]; then
      parsing=false
      shift
      continue
    fi
    options+=("$1")
    shift
  done

  if [[ ! -t 0 || ! -t 1 || ${#options[@]} -eq 0 ]]; then
    local i choice
    say "$prompt"
    for i in "${!options[@]}"; do
      note "  $((i + 1)). ${options[$i]}"
    done
    printf '  %s> %s' "$BOLD" "$RESET"
    read -r choice || true
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#options[@]} )); then
      printf -v "$out_name" '%s' "${options[$((choice - 1))]}"
    elif [[ -n "$choice" ]]; then
      printf -v "$out_name" '%s' "$choice"
    else
      if (( default_idx >= 0 && default_idx < ${#options[@]} )); then
        printf -v "$out_name" '%s' "${options[$default_idx]}"
      else
        printf -v "$out_name" '%s' "${options[0]}"
      fi
    fi
    return 0
  fi

  local cursor=0 i line_count=0 key
  if [[ "$default_idx" =~ ^[0-9]+$ ]] && (( default_idx >= 0 && default_idx < ${#options[@]} )); then
    cursor=$default_idx
  fi

  _menu_hide_cursor
  trap '_menu_show_cursor' RETURN

  while true; do
    if (( line_count > 0 )); then
      _menu_clear_lines "$line_count"
    fi
    line_count=0

    printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
    line_count=$((line_count + 1))
    for i in "${!options[@]}"; do
      local prefix="  "
      [[ $i -eq $cursor ]] && prefix="${BLUE}> "
      local marker=" "
      [[ $i -eq $cursor ]] && marker="•"
      printf '%s%s %s\n' "$prefix" "$marker" "${options[$i]}"
      line_count=$((line_count + 1))
    done
    printf '  %sUse ↑/↓ to move, Enter to confirm%s\n' "$DIM" "$RESET"
    line_count=$((line_count + 1))

    read_key || continue
    key="$REPLY"
    case "$key" in
      up)    cursor=$(((cursor - 1 + ${#options[@]}) % ${#options[@]})) ;;
      down)  cursor=$(((cursor + 1) % ${#options[@]})) ;;
      enter) break ;;
      space) break ;;
      quit) break ;;
    esac
  done

  _menu_clear_lines "$line_count"
  printf -v "$out_name" '%s' "${options[$cursor]}"
}

# Single-select with full-screen redraw — best for back-to-back wizard prompts.
# Usage: select_one_framed OUT_VAR_NAME REDRAW_FN [--default idx] -- OPTION ...
select_one_framed() {
  local out_name="$1" redraw_fn="$2"
  shift 2
  local default_idx=-1 options=() parsing=true

  while (( $# )); do
    if $parsing && [[ "$1" == "--default" ]]; then
      shift
      default_idx="${1:--1}"
      shift
      continue
    fi
    if $parsing && [[ "$1" == "--" ]]; then
      parsing=false
      shift
      continue
    fi
    options+=("$1")
    shift
  done

  if [[ ! -t 0 || ! -t 1 || ${#options[@]} -eq 0 ]]; then
    "$redraw_fn"
    note ""
    local i choice
    for i in "${!options[@]}"; do
      note "  $((i + 1)). ${options[$i]}"
    done
    printf '  %s> %s' "$BOLD" "$RESET"
    read -r choice || true
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#options[@]} )); then
      printf -v "$out_name" '%s' "${options[$((choice - 1))]}"
    elif [[ -n "$choice" ]]; then
      printf -v "$out_name" '%s' "$choice"
    else
      if (( default_idx >= 0 && default_idx < ${#options[@]} )); then
        printf -v "$out_name" '%s' "${options[$default_idx]}"
      else
        printf -v "$out_name" '%s' "${options[0]}"
      fi
    fi
    return 0
  fi

  local cursor=0 i key prefix marker
  if [[ "$default_idx" =~ ^[0-9]+$ ]] && (( default_idx >= 0 && default_idx < ${#options[@]} )); then
    cursor=$default_idx
  fi

  _menu_hide_cursor
  trap '_menu_show_cursor' RETURN

  while true; do
    _clear
    "$redraw_fn"
    note ""
    for i in "${!options[@]}"; do
      prefix="  "
      marker=" "
      if [[ $i -eq $cursor ]]; then
        prefix="${BLUE}> "
        marker="•"
      fi
      printf '%s%s %s\n' "$prefix" "$marker" "${options[$i]}"
    done
    note "Use ↑/↓ to move, Enter to confirm"

    read_key || continue
    key="$REPLY"
    case "$key" in
      up)    cursor=$(((cursor - 1 + ${#options[@]}) % ${#options[@]})) ;;
      down)  cursor=$(((cursor + 1) % ${#options[@]})) ;;
      enter|space) break ;;
      quit) break ;;
    esac
  done

  printf -v "$out_name" '%s' "${options[$cursor]}"
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ Saved%s\n' "$GREEN" "$RESET"
}

write_env_quiet() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  All done!%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#WRITTEN_ENV[@]} )); then
    note "Your choices have been saved."
  fi
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "One small thing left to do:"
    for s in "${SKIPPED[@]}"; do note "  • $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — RealtorOS launch wizard
# ──────────────────────────────────────────────────────────────────────────

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.realtor-preferences.env"
PREFS_JSON="$ROOT/apps/web/public/realtor-preferences.json"

if [[ -f "${HOME}/.local/share/realtor-os/install.env" ]]; then
  # shellcheck source=/dev/null
  source "${HOME}/.local/share/realtor-os/install.env"
fi
export REALTOR_REPO_ROOT="$ROOT"
export REALTOR_INSTALL_DIR="${REALTOR_INSTALL_DIR:-$ROOT}"
export REALTOR_ISOLATED="${REALTOR_ISOLATED:-1}"
# shellcheck source=scripts/realtor-env.sh
source "$ROOT/scripts/realtor-env.sh"
export REALTOR_REPO_ROOT="$ROOT"
export REALTOR_INSTALL_DIR="${REALTOR_INSTALL_DIR:-$ROOT}"

TOTAL_STAGES=9

cmd_exists() { command -v "$1" >/dev/null 2>&1; }

node_major_version() {
  node -p "process.versions.node.split('.')[0]" 2>/dev/null || echo 0
}

activate_fnm_env() {
  local fnm_dir="${HOME}/.local/share/fnm"
  export PATH="${fnm_dir}:${HOME}/.local/bin:${PATH}"
  if [[ -x "${fnm_dir}/fnm" ]]; then
    # shellcheck disable=SC2046
    eval "$("${fnm_dir}/fnm" env)"
  fi
}

install_node_with_wizard() {
  step "Installing Node.js 22 LTS (one moment)…"
  if bash "$ROOT/scripts/install-node.sh"; then
    activate_fnm_env
    hash -r 2>/dev/null || true
    ok_msg "Node.js installed ($(node --version))"
    return 0
  fi
  warn "Automatic Node.js install failed."
  return 1
}

node_manual_install_hint() {
  open_url "https://nodejs.org/en/download"
  step "Download the LTS installer from that page, install it, then run this setup again:"
  note "  bash scripts/launch-wizard.sh"
}

install_git_with_wizard() {
  step "Installing Git (one moment)…"
  local status=0
  bash "$ROOT/scripts/install-git.sh" || status=$?
  if (( status == 0 )) && cmd_exists git; then
    ok_msg "Git installed ($(git --version))"
    return 0
  fi
  if (( status == 2 )); then
    warn "Complete the system installer, then run this wizard again."
    return 1
  fi
  warn "Automatic Git install failed."
  return 1
}

git_manual_install_hint() {
  open_url "https://git-scm.com/downloads"
  step "Install Git from that page if you want to clone or pull updates later."
}

check_claude_login() {
  cmd_exists claude || return 1
  claude auth status 2>/dev/null | grep -q '"loggedIn"[[:space:]]*:[[:space:]]*true'
}

check_codex_login() {
  cmd_exists codex || return 1
  codex login status 2>&1 | grep -qi 'logged in'
}

check_kimi_login() {
  cmd_exists kimi || return 1
  [[ -d "${HOME}/.kimi-code/credentials" ]] || return 1
  [[ -n "$(ls -A "${HOME}/.kimi-code/credentials" 2>/dev/null || true)" ]]
}

ok_msg() {
  printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"
}

guide_login() {
  local name="$1"
  local login_cmd="$2"
  local check_fn="$3"

  if "$check_fn"; then
    ok_msg "You are signed in to ${name}"
    return 0
  fi

  warn "You are not signed in to ${name} yet."
  say "We will start the sign-in for you right here."
  say "Follow the instructions below — a browser window may open."
  note ""
  pause "Press Enter to start sign-in"

  say "Starting sign-in for ${name}..."
  note ""
  if $login_cmd; then
    if "$check_fn"; then
      ok_msg "You are signed in to ${name}"
      return 0
    fi
  fi

  warn "Sign-in for ${name} did not finish."
  if confirm "Try again"; then
    say "Starting sign-in for ${name}..."
    note ""
    $login_cmd || true
    if "$check_fn"; then
      ok_msg "You are signed in to ${name}"
      return 0
    fi
  fi

  SKIPPED+=("Sign in to ${name}")
  return 1
}

PICK_AGENT=""

models_step_draw() {
  stage_refresh "Pick your default AI models"
  say "Each assistant can use different models (think of them as different"
  say "versions of the same AI — some faster, some smarter)."
  say "You can change these anytime in the app."

  local any_done=false
  if $USE_CLAUDE && [[ -n "${MODEL_CLAUDE:-}" ]]; then
    ok_msg "Claude — ${MODEL_CLAUDE}"
    any_done=true
  fi
  if $USE_CODEX && [[ -n "${MODEL_CODEX:-}" ]]; then
    ok_msg "Codex — ${MODEL_CODEX}"
    any_done=true
  fi
  if $USE_KIMI && [[ -n "${MODEL_KIMI:-}" ]]; then
    ok_msg "Kimi — ${MODEL_KIMI}"
    any_done=true
  fi

  if [[ -n "${PICK_AGENT:-}" ]]; then
    note ""
    printf '  %sChoose a model for %s:%s\n' "$BOLD" "$PICK_AGENT" "$RESET"
  elif $any_done; then
    note ""
    ok_msg "All models chosen"
  fi
}

pick_model() {
  local agent="$1"
  local var_name="$2"
  shift 2
  local options=("$@")
  local current default_idx=-1 i

  current=$(_existing "REALTOR_${var_name}" || true)
  for i in "${!options[@]}"; do
    if [[ -n "$current" && "${options[$i]}" == "$current" ]]; then
      default_idx=$i
      break
    fi
  done

  local default_args=()
  if (( default_idx >= 0 )); then
    default_args=(--default "$default_idx")
  fi

  PICK_AGENT="$agent"
  select_one_framed "$var_name" models_step_draw "${default_args[@]}" -- "${options[@]}"
  PICK_AGENT=""
}

write_preferences_json() {
  local agents_csv="$1"
  mkdir -p "$(dirname "$PREFS_JSON")"
  node - "$PREFS_JSON" "$agents_csv" \
    "${MODEL_CLAUDE:-}" "${MODEL_CODEX:-}" "${MODEL_KIMI:-}" <<'NODE'
const fs = require('node:fs');
const [path, agentsCsv, claude, codex, kimi] = process.argv.slice(2);
const models = {};
for (const [agent, value] of [['claude', claude], ['codex', codex], ['kimi', kimi]]) {
  if (value) models[agent] = value;
}
const agents = agentsCsv.split(',').map((s) => s.trim()).filter(Boolean);
const payload = {
  agents,
  models,
  defaultAgent: agents[0] ?? 'kimi',
};
fs.writeFileSync(path, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
console.log(`  ✓ Saved your preferences`);
NODE
}

banner "RealtorOS — let's get you chatting"

# ── 1. Node.js + Git ────────────────────────────────────────────────────────
stage "Is your computer ready?"
activate_fnm_env
say "RealtorOS needs Node.js to run."
say "Let's check — and install it for you if it's missing."
if cmd_exists node; then
  NODE_MAJOR="$(node_major_version)"
  say "Node.js is present ($(node --version))."
  if (( NODE_MAJOR < 20 )); then
    warn "This version is too old (need 20+)."
    if confirm "Install Node.js 22 LTS now"; then
      install_node_with_wizard || { node_manual_install_hint; exit 1; }
    else
      node_manual_install_hint
      exit 1
    fi
  fi
else
  warn "Node.js isn't installed yet."
  if confirm "Install Node.js 22 LTS now (recommended)"; then
    install_node_with_wizard || { node_manual_install_hint; exit 1; }
  else
    node_manual_install_hint
    exit 1
  fi
fi

note ""
say "Git is only needed for git clone/pull (optional)."
if cmd_exists git; then
  ok_msg "Git is installed ($(git --version))"
elif [[ "${REALTOR_ISOLATED:-1}" == "1" ]]; then
  note "Isolated install: Git not required — the app already lives in this folder."
  note "Future updates: curl -fsSL https://raw.githubusercontent.com/nativestrider/realtor-os/main/scripts/install.sh | bash"
else
  warn "Git isn't installed."
  if confirm "Install Git now (may use sudo on Linux)"; then
    install_git_with_wizard || git_manual_install_hint
  else
    note "Skipping Git — you can still run RealtorOS from this folder."
  fi
fi
pause "Press Enter to continue"

# ── 2. pnpm + project dependencies ────────────────────────────────────────
stage "Getting the app ready"
cd "$ROOT"
say "Now we'll download the RealtorOS app files to your computer."
say "This only happens once — and it may take a minute."
if ! cmd_exists pnpm; then
  step "Setting up the download tool (one moment)..."
  if cmd_exists corepack; then
    corepack enable >/dev/null 2>&1 || true
    corepack prepare pnpm@10.28.0 --activate >/dev/null 2>&1 || true
  fi
fi
if ! cmd_exists pnpm; then
  warn "We couldn't set up the download tool automatically."
  open_url "https://pnpm.io/installation"
  step "Follow the install guide on that page, then run this setup again."
  exit 1
fi
step "Downloading now — grab a coffee ☕"
if ! pnpm install; then
  warn "Download failed. Check your internet connection and try again."
  exit 1
fi
mkdir -p "${REALTOR_HOME}/pnpm-store" "${PNPM_HOME}"
pnpm config set store-dir "${REALTOR_HOME}/pnpm-store" 2>/dev/null || true
printf '  %s✓ App is ready%s\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 2b. Playwright Chromium (Zillow import) ───────────────────────────────
stage "Browser for Zillow imports"
say "To import or verify listings from Zillow, agents open a local Chrome window"
say "(Playwright Chromium). This is separate from the RealtorOS web app."
note ""
BROWSER_MANIFEST="${REALTOR_DATA_DIR:-$HOME/.realtor-os}/browser.json"
if [[ -f "$BROWSER_MANIFEST" ]]; then
  ok_msg "Playwright Chromium is already installed"
else
  say "We recommend installing it now (~200 MB download, one time)."
  if confirm "Install Playwright Chromium now"; then
    step "Downloading Chromium…"
    if pnpm run setup:browsers; then
      ok_msg "Browser ready for Zillow import"
    else
      warn "Browser install failed. You can retry later with: pnpm run setup:browsers"
      note "On Linux you may also need: pnpm run setup:browsers:deps"
    fi
  else
    SKIPPED+=("Playwright browser — run later: pnpm run setup:browsers")
    note "Zillow import/verify will not work until you run: pnpm run setup:browsers"
  fi
fi
pause "Press Enter to continue"

# ── 3. Choose assistants ──────────────────────────────────────────────────
stage "Which AI assistants do you use?"
say "RealtorOS lets you chat with AI tools you already have on your computer."
say "Pick one or more — you need at least one."
note ""

ASSISTANT_LABELS=("Claude (by Anthropic)" "Codex (by OpenAI / ChatGPT)" "Kimi (by Moonshot)")
ASSISTANT_IDS=("claude" "codex" "kimi")

DEFAULT_ASSISTANT_IDXS=()
saved_agents=$(_existing REALTOR_SELECTED_AGENTS || true)
if [[ -n "$saved_agents" ]]; then
  IFS=',' read -ra _saved_list <<< "$saved_agents"
  for i in "${!ASSISTANT_IDS[@]}"; do
    for saved in "${_saved_list[@]}"; do
      saved="${saved// /}"
      if [[ "${ASSISTANT_IDS[$i]}" == "$saved" ]]; then
        DEFAULT_ASSISTANT_IDXS+=("$i")
      fi
    done
  done
fi

SELECTED_IDXS=()
multiselect "Choose your assistants:" SELECTED_IDXS \
  --default "${DEFAULT_ASSISTANT_IDXS[@]}" -- \
  "${ASSISTANT_LABELS[@]}"

USE_CLAUDE=false
USE_CODEX=false
USE_KIMI=false
SELECTED_AGENTS=()

for idx in "${SELECTED_IDXS[@]}"; do
  case "${ASSISTANT_IDS[$idx]}" in
    claude) USE_CLAUDE=true; SELECTED_AGENTS+=("claude") ;;
    codex) USE_CODEX=true; SELECTED_AGENTS+=("codex") ;;
    kimi) USE_KIMI=true; SELECTED_AGENTS+=("kimi") ;;
  esac
done

if ! $USE_CLAUDE && ! $USE_CODEX && ! $USE_KIMI; then
  warn "Please pick at least one assistant to continue."
  exit 1
fi

AGENTS_CSV=$(IFS=,; echo "${SELECTED_AGENTS[*]}")
write_env REALTOR_SELECTED_AGENTS "$AGENTS_CSV"
say "Great — you picked: ${AGENTS_CSV}"
pause "Press Enter to continue"

# ── 4. Verify CLI tools are installed ─────────────────────────────────────
stage "Checking your AI apps are installed"
say "Each AI assistant needs its own app installed on your computer."
say "Let's make sure you have the ones you picked."

verify_cli() {
  local name="$1" cmd="$2" url="$3"
  if cmd_exists "$cmd"; then
    printf '  %s✓ %s is installed%s\n' "$GREEN" "$name" "$RESET"
    return 0
  fi
  warn "${name} doesn't seem to be installed yet."
  open_url "$url"
  step "Follow the install guide on that page, then run this setup again."
  SKIPPED+=("Install ${name} — see ${url}")
  return 1
}

CLI_OK=true
$USE_CLAUDE && verify_cli "Claude Code" claude "https://docs.anthropic.com/en/docs/claude-code/overview" || CLI_OK=false
$USE_CODEX && verify_cli "Codex" codex "https://developers.openai.com/codex/cli/" || CLI_OK=false
$USE_KIMI && verify_cli "Kimi" kimi "https://www.kimi.com/code/docs/en/kimi-code-cli/guides/getting-started.html" || CLI_OK=false

if ! $CLI_OK; then
  warn "Install what's missing above, then run this setup again."
  finish
  exit 1
fi
pause "Press Enter to continue"

# ── 5. Sign-in checks ───────────────────────────────────────────────────────
stage "Are you signed in?"
say "Before you can chat, each AI needs you to be logged in on this computer."
say "We will check now and walk you through sign-in if needed."

LOGIN_OK=true
$USE_CLAUDE && guide_login "Claude" "claude auth login" check_claude_login || LOGIN_OK=false
$USE_CODEX && guide_login "Codex" "codex login" check_codex_login || LOGIN_OK=false
$USE_KIMI && guide_login "Kimi" "kimi login" check_kimi_login || LOGIN_OK=false

if ! $LOGIN_OK; then
  warn "Please complete sign-in above, then run this setup again:"
  note "  bash scripts/launch-wizard.sh"
  finish
  exit 1
fi
pause "Press Enter to continue"

# ── 6. Choose default models ────────────────────────────────────────────────
stage "Pick your default AI models"

MODEL_CLAUDE=""
MODEL_CODEX=""
MODEL_KIMI=""

if $USE_CLAUDE; then
  pick_model "Claude" MODEL_CLAUDE default sonnet opus haiku
  write_env_quiet REALTOR_MODEL_CLAUDE "$MODEL_CLAUDE"
fi
if $USE_CODEX; then
  pick_model "Codex" MODEL_CODEX default gpt-5.4 gpt-5.3-codex o4-mini
  write_env_quiet REALTOR_MODEL_CODEX "$MODEL_CODEX"
fi
if $USE_KIMI; then
  pick_model "Kimi" MODEL_KIMI default kimi-k2-turbo-preview moonshot-v1-8k
  write_env_quiet REALTOR_MODEL_KIMI "$MODEL_KIMI"
fi

_clear
models_step_draw
write_preferences_json "$AGENTS_CSV"
pause "Press Enter to continue"

# ── 7. Ready to launch ──────────────────────────────────────────────────────
stage "Ready to open the chat"
say "Everything is set! Here's what you picked:"
note ""
$USE_CLAUDE && note "  Claude — model: ${MODEL_CLAUDE:-default}"
$USE_CODEX && note "  Codex — model: ${MODEL_CODEX:-default}"
$USE_KIMI && note "  Kimi — model: ${MODEL_KIMI:-default}"
note ""
say "We'll open the chat in your browser now."
say "Keep this window open while you chat."
say "When you're done, come back here and press Ctrl-C to close the app."

if ! confirm "Open RealtorOS now"; then
  say "No rush! Whenever you're ready, just run:"
  note "  bash scripts/launch-wizard.sh"
  finish
  exit 0
fi

# ── 8. Launch ───────────────────────────────────────────────────────────────
stage "Opening RealtorOS"
realtor_show_logo "$BOLD" "$DIM" "$BLUE" "$RESET"
LAUNCHER="$(bash "$ROOT/scripts/write-launcher.sh" "$ROOT")"
say "User-local shortcut: ${LAUNCHER}"
note "Add ~/.local/bin to your PATH to run: realtor-os"
say "Starting up — your browser will open in a moment…"
cd "$ROOT"
exec bash -c 'source scripts/realtor-env.sh && export REALTOR_REPO_ROOT="'"$ROOT"'" && node packages/cli/bin/realtor.mjs web'
